### ISSUE TITLE
bug regarding deleted comments

### ISSUE THREAD

**Issue by daveloyall** [benbalter/benbalter.github.com#100]
Hm, maybe it's a disqus bug.  http://ben.balter.com/2014/01/27/open-collaboration/ shows `0 comments, be the first to comment` in once place on the page, but inside `<ul class="discovery-posts">` there is a copy of the comment.  ctrl-F5 did not remove it so I don't think it is a caching issue.  Good luck!

**Comment by benbalter** [comment]
You're exactly right. Looks like it has to do with correcting a typo in the post url. WIll take a look and see about transferring.

**Comment by benbalter** [comment]
It seems https://github.com/benbalter/benbalter.github.com/commit/892f4484db0282f6a04f60e3d12abc9128abfd2d#diff-dede3e83bbc05615e723232e2a2a80da broke the URL, which gave the discussion a new ID. I put in a migration request, which should hopefully merge the threads when run. Thanks for the heads up!
