### ISSUE TITLE
How to identify a strong open source project

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#118]
- Recently and frequently updated
- Recently opened (and closed) issues
- Number of issues, forks, stars
- Overall documentation
- Org or user account
- Backed by an organization

![screen shot 2014-05-31 at 2 51 30 pm](https://cloud.githubusercontent.com/assets/282759/3139851/9f8867b2-e8f4-11e3-8934-7b7a517acf55.png)

(via http://www.slideshare.net/benbalter/making-your-wordpress-site-more-shareable-sociable-and-likeable)

**Comment by parkr** [comment]
Thoughts on metrics specific to other platforms, such as SourceForge? GitHub is awesome for most things, but RubyGems/NPMJS.org downloads, activity on mailing lists, etc are also helpful to gauge how strong an OSS is.
