### ISSUE TITLE
which CC license for content?

### ISSUE THREAD

**Issue by willnorris** [benbalter/benbalter.github.com#128]
- [readme.md](https://github.com/benbalter/benbalter.github.com/blob/d14ae62706a9a167a750e434fc633041f7a7983f/readme.md) says [BY-NC-SA](http://creativecommons.org/licenses/by-nc-sa/3.0/)
- [fine-print.md](https://github.com/benbalter/benbalter.github.com/blob/d14ae62706a9a167a750e434fc633041f7a7983f/fine-print.md) says [BY](http://creativecommons.org/licenses/by/3.0/)

one of those should probably be updated.

**Comment by benbalter** [comment]
Thanks for the heads up. Both reference CC-BY now.
