### ISSUE TITLE
Why isn't all government software open source?

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#131]
Via https://twitter.com/kijanawoodard/status/494135505076776963

**Comment by kijanawoodard** [comment]
I've been wondering about this for quite a while now. From local government all the way to national. I've yet to see a compelling reason that the software can not and should not be OSS. 

Furthermore, accepting pull requests would result in 
- increased cohesion with citizens
- decreasing the cost of production
- changing the role of the primary contractor to that of primary maintainer

**Comment by parkr** [comment]
In an ideal world, I think what you've said is true, @kijanawoodard. I don't think we have enough evidence at the scale you mention to conclude that it would lead to those three things you list. I am already overwhelmed with the open-source world as it is – how will adding hundreds of thousands of projects (all with varying amounts to no documentation) allow for such cohesion and decreased cost as you say? It seems to me that the time available for each user to contribute is already stretched quite thinly and adding ever more projects to the mix won't mean they have more time.

The only answer I can come up with is that increased government employee and contractor activity/presence on GitHub/similar platform = greater # of folks to help out and increased support from unrelated gov'tl devs helping fix up code for a slightly different use case.

Anyway, I definitely agree with what you said in an ideal world. I'm just not sure it'd play out that way if all projects were to be made open-source today.

Looking forward to your post, Ben!

**Comment by kijanawoodard** [comment]
Fortunately, we have the benefit of time and inertia. All the projects won't come online at once. :-D

Set the principle of OSS and start the process.

The "popular" projects will get attention first. Maybe no one cares about the Smithsonian cafeteria software right away ... but, back to the original point, why hide it at all?

In the meantime, I'd wager that just having continually more source code in public view will change the behavior of the primary contractors. "Heisenberg's uncertainty [of being embarrassed] principle" applied to software.

It will be funny to see $300 million dollars worth of "enterprise architecture" get dismantled, piece by piece, on the blog of a high school kid.

Of course, I'd also wager that an enormous amount of difficulty faced by the primary contractors is that the "specs" are beyond terrible and the feedback loop is non-existent.

**Comment by joeyguerra** [comment]
Does it have to be LAW that all govt. software is open sourced?

**Comment by benbalter** [comment]
Took a pass at answering this over in https://github.com/benbalter/benbalter.github.com/pull/133.

**Comment by benbalter** [comment]
[Much longer answer](http://ben.balter.com/2014/08/03/why-isnt-all-government-software-open-source/). :smile:
