### ISSUE TITLE
10 things every hotel room should have

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#137]
1. When I get off the elevator, I need a sign to tell me which way my room is
2. Outlets, immediately visible, at waste level. Not wedged into a desk so that adapters don't fit. Not behind the desk, not on the side of the desk. Don't make me hunt for them.
3. A single light switch with three modes, on, off, night - http://i.imgur.com/x9j2aGz
4. Ample counter space in the bathroom. I need someplace to put my product
5. A mirror I can get close to
6. Water. I'm your guest. It's considerate.
7. A list of TV channels directly adjacent to the TV. Not buried in a 300 page book along side the restaurant hours. 
8. A safe (with an electrical outlet)
9. WiFi that's faster than dialup
   10.

**Comment by parkr** [comment]
> at waste level

at _waist_ level? or at _waste basket_ level?

> A single light switch with three modes, on, off, night

Wat? `night` mode?

:+1:

**Comment by Merovex** [comment]
I know this is long past, but with the Hue Tap for Hue bulbs, my lights do have Bright, Cozy, Night, Off. No Ooo!, though.
