### ISSUE TITLE
Government Attorneys: Everything you need to know about open source software licensing

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#155]
/cc @gbinal and @adelevie and @konklone if you have any suggestions / requests.

Advice is going to take the long road through 17 USC § 105 to recommend CC0 unless it's copyleft, but holler if there are any other gotchas worth calling out.

**Comment by konklone** [comment]
If you felt motivated and like it was worth it, you could proactively reassure government lawyers that it's okay for government employees to contribute their work upstream to an existing copyleft (GPL or MIT) project even though they don't have copyright to license. (See [this FSF FAQ question](http://www.gnu.org/licenses/gpl-faq.html#GPLUSGov) and the one right below it.)

You may find the [HISTORY.md](https://github.com/unitedstates/licensing/blob/gh-pages/HISTORY.md) doc we've been keeping over at [unitedstates/licensing](https://github.com/unitedstates/licensing) helpful as a link/research jumping ground. @joshdata and I have been keeping that file up to date pretty well.

**Comment by benbalter** [comment]
Need to clean things up and link out to resources, but took an initial pass over in #159 if there's anything that strikes you as missing. Would this be helpful as a primer to start discussions with general counsel's offices?
