### ISSUE TITLE
Share Your Understanding of Jekyll Collections

### ISSUE THREAD

**Issue by parkr** [benbalter/benbalter.github.com#207]
Hey Ben,

I admire your lucid writing style and was wondering whether you'd be willing to apply that to Jekyll's [Collections](http://jekyllrb.com/docs/collections/) feature. You have been a champion of them since we introduced the feature last year. A few key questions:

- [What are collections? Explain to me like I'm 5.](http://www.reddit.com/r/Jekyll/comments/2op4ip/explain_collections_to_me_like_im_5/)
- How do they differ from pages?
- What should I use them for? Why do that over a straight pages solution?
- How do I configure them if, say, I want a different permalink instead of `/collection_name/doc_path`?

Use-cases will be especially helpful. Let me know what you think! Thank you. :smile:

**Comment by benbalter** [comment]
@parkr any feedback on https://github.com/benbalter/benbalter.github.com/pull/218 by chance? :smile:

**Comment by parkr** [comment]
:eyes:
