### ISSUE TITLE
Add tags to posts / Navigate to previous posts.

### ISSUE THREAD

**Issue by melodykramer** [benbalter/benbalter.github.com#223]
Hey Ben, I love your site so much that I forked it and am slowly working on an iteration for my site. Two  things that I think would improve the experience for the reader is to

a) add tags / categories on the page. 
b) add the ability to navigate to the previous and next post on the page

I'm going to try to work on these this week.

**Comment by benbalter** [comment]
> a) add tags / categories on the page. 

To each their own. :smile: I had them for a while and actually pulled them out as being too distracting (both for my own writing, and for the reader). It's hard to do tag/category archives with vanilla Jekyll, especially as the number of posts/tags grow. I also found that my writing was clustered around a few tags, making their value questionable. Last, analytics showed folks weren't browsing by tags, neither on my old WordPress site, nor on Jekyll, but your mileage may vary.

> add the ability to navigate to the previous and next post on the page

Easy peasy, and I'd :heart: a pull request, if you do. 

You'll want [`{{ page.next }}` and `{{ page.previous }}`](http://jekyllrb.com/docs/variables/#page-variables).

**Comment by melodykramer** [comment]
Thanks! I'll work on that next weekend :+1:

**Comment by benbalter** [comment]
Closing in favor of less noise, as Disqus automatically includes links to related posts (and posts are not necessarily related chronologically).
