### ISSUE TITLE
The difference between 18F and USDS

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#232]
One ships culture ("work like we do") the other ships confidence ("we're on it, boss"). 

Also in that a win for 18F would be for a customer agency to be on the front page of the NYT, taking credit for 18F's work, for USDS it's that the project *didn't* make the cover of the NYT, and nobody ever knew they were there.

Think Hitch versus Men in Black.

**Comment by quepol** [comment]
Do you have a bug or a mole at 1800 F St.? ;)
Great post!

**Comment by benbalter** [comment]
Ha. I wouldn't need one. Y'all's workflow already captures and exposes process.

Just following my rule of if you're asked the same question multiple times, the answer better have a URL. :smile:
