### ISSUE TITLE
The top ___ reasons why developers don't want to work at your agency

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#236]
* I have to make the case for why I should be able to use the computer of my choice (read: non-locked down Dell)
* Developers almost never get `sudo` access to their computer, a daily necessity to support any software development workflow (needed to install development tools and frameworks, upgrade dependencies, etc.)
* WiFi is the exception, not the norm
* I have to make the case for why the agency should use the industry-standard cloud services that I know and :heart: (Heroku, AWS, Travis, GitHub, etc.)
* Continuous integration is often a cutting-edge development concept
* Continuous delivery is measured in days, not minutes (shout out change control boards!)
* Agile is something still talked about, as if there's a viable alternative
* The final deliverable for multi-million dollar contracts is an email with a zipped attachment of the code; agencies often don't have day-to-day visibility into the project's progress (read: version control and shared issue tracking)
* Modern frameworks are assumed to be insecure unless I prove otherwise (Rails, Node, even PHP are looked at as too immature compared Sharepoint, Coldfusion, etc.)
* Open source is still something you do, not who you are or how you work
* Working in the open is a novelty, not a best practice
* Speaking at conferences is tightly controlled by a non-technical public affairs office
* Unless they transition to management, geeks are always the bottom of the bureaucratic food chain regardless of seniority or skill
* Agencies don't trust their employees
* Culture only happens outside of working hours (lunch, happy hour)
* If you're passionate about a specific topic, ethics restrictions make it difficult to transition to/from the private sector
* The hiring process is measured in months, is opaque and arms-length
* Recruitment is almost unheard of

**Comment by konklone** [comment]
:+1:

**Comment by sebie** [comment]
Thank you!

Deffenitly deserves a :+1: .

**Comment by benbalter** [comment]
:ship:'d http://ben.balter.com/2015/04/21/why-technologists-dont-want-to-work-at-your-agency/
