### ISSUE TITLE
Copyright notice for websites and open source projects

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#254]
Via https://github.com/github/choosealicense.com/pull/264. 

:warning: Draft comment :warning: to be turned into a longer blog post:

In short, it should be `2013 - 2015, GitHub, Inc. and the choosealicense.com contributors`.

Longer answer:

*(IANYL, so please consult your own legal counsel before making decisions regarding how you license your own projects.)*

### Do you need a copyright notice at all? 

The whole point of putting :copyright: on anything is because in ye olden days (before 1979), it was a requirement that the publisher mark their work in order to secure their copyright under the Copyright Act. After the US became a signatory of the Berne convention, that requirement was dropped, and copyright now vests in the author at the time of publication.

Today, explicit copyright notices in licenses, footers (or really in general), besides for being a great way to fill empty space and perpetuating legal FUD, really only serve to put a potential infringer on notice and offsets the "Oh yeah, well I didn't know it was copyrighted" claim sniff test. It's a nice to have thing, but strictly speaking, isn't necessary.

### When is a digital work "published"?

Okay, so we're going to include a copyright notice since we've been doing it forever, and per the link above, we need to note the year of the first publication. When is an open source project (or a website, as that's the most common means of publishing an open source project, e.g., via GitHub's web interface) "published"? Clearly in this case, choosealicense.com was "published" when the site launched in 2013. But, as this is open source, things are never finished, and we actually "published" copyrighted content in 2014 and 2015 (e.g., a pull request merged on 1/1/2015 would contain copyright content "first published" in 2015). 

There's precedent for this, if you ever look at the copyright page of an IRL book. It'll likely say copyright 2001, 2004, 2006-2007, etc., noting each year of publication. Here, the same legal theory is at play, we're just unbridled from the confines of the physical world, and thus :ship: a bit more frequently. 

If you have a page that updates daily (think the front page of nytimes.com), then the current year is sufficient, because everything on that page was "published" that year, and thus received copyright that year. If you have a page where some stuff was "published" in 2013, and some in 2014 (think choosealicense.com), then to really properly put a potential infringer on notice you'd want [original publish date] - [last published date].  

Take for example, if on Dec 15 2014 Ida Infringer copies choosealicense.com and starts selling *Open Source Licensing For Dummies*, but does so in a way that violates her license (e.g., she doesn't attribute our original work). On Jan 1st 2015 the contributors of chooselicense.com take Ida to court to enforce our rights to have Ida attribute the work to us. We can't as easily say "judge, but it clearly says © 2014!" if the alleged infringement occurred prior to when we're explicitly claiming copyright (or if it's clear we're claiming a 2013 copyright in content that was authored in 2014). Again, the value here is really for that sniff test, but if you're going to do it, I'd argue that you should  accurately reflect (aka accurately notice) the true copyright.

### Who should be listed as the copyright holder

* Difference between copyright and license
* About how you retain copyright
* It should be the contributors (or contributors + maintainer) not just the maintainer

**Comment by bkeepers** [comment]
I'd like to challenge the notion that the year is even required for the notice. What value does it provide? I'm guessing the greatest value is in resolving disputes, but a git history will be much more suitable for that.

```
Copyright (c) GitHub, Inc. and the choosealicense.com contributors.
```
