### ISSUE TITLE
Why URLs

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#301]
* Humans have a terrible fidelity for retaining context, process, and decision pedigree
* URLs make context time and location agnostic
  * Counters the "you had to be there, go ask Bob"-ness of most synchronous workflows 
  * Members regularly join your team mid decision or after a decision is made
  * Ability to link related concepts to prior art and ground discussions in the tangible
* URLs service as artifacts for what decisions was made, why it was made, and who made it 
* Also capture what other alternatives were considered and why they were rejected
* Giving something a URL forces the moving party to distill their ideas down to written form, to capture the essential elements of their proposal and articulate it in the clearest way possible
* "**Reduce** to writing" -> distill to what matters
* Having a URL is distinct from the scope in which something is shared. Can be URL'd to 1, 2, 100, or 6 Billion people
* Ask yourself how has your workflow changed since the cold war, if at all? Since the advent of the internet?
* What's the virtue of a URL that nobody can access other than the author? (e.g. GMail URLs)
* URL is what separates the internet from the web (concentric circles with URL on the boundary between web and internet)

See also http://ben.balter.com/2014/10/07/expose-process-through-urls/

**Comment by benbalter** [comment]
Also to note, need to distinguish something having a URL from something having a GitHub-style, open to everyone comment forum:
1. Can have a URL that exposes context that is read only (e.g. a chat transcript)
2. Can have a URL that exposes context to a select group, without exposing that context to the world, entire organization, etc.
3. Can have a URL that exposes context after the fact (e.g., imagine "open sourcing" an issue once it's closed)

**Comment by benbalter** [comment]
Another edge case to consider:

What about sensitive conversations? When someone gets fired? Salary negotiations? Interpersonal conflicts? Legal disputes? In my mind those transaction should all have URLs. I shouldn't have access to the content if I were not otherwise involved, but if I were designing the ideal way for an organization to work, It'd be far preferable for there to be a digital record capturing who, how, and why each decision was made, available to those that were part of the decision, than for it to to only exist on paper, in the hallways, or in unspoken sentiment, which a flood, career change, or memory lapse can wipe out entirely (and isn't shareable, etc. as other members join the team).

**Comment by spraints** [comment]
One barrier that might be the technical nature of URLs. They feel really approachable to me, but I assume that people who aren't engineers are less likely to find them as approachable. Or, the nature of the job might be that you do a lot of things that are hard to capture in a tangible form, or that are unimportant to capture electronically. I could imagine being on a team and feeling like "URL all the things" was a mandate to make my process conform to someone else's idea of working. Regardless of whether there are URLs, I think that teams within a company should define their interface to the rest of the company. Where can others look for your work output? Where can others ask general questions or start a conversation with your team? I like to learn about what other people are doing, and URLs are a great way for a shy person like me to find out. It's great to email `info@whatever.com` and hear back from someone, it's much less great to email `info@whatever.com` and hear nothing back when I should have called 800-WHA-TEVS instead.

**Comment by bkeepers** [comment]
All good thoughts.

I wonder if anything can be drawn from an analogy to a photograph. Some questions that come to mind: Why do you take a photo? What is worth taking a photo of? Who do you share the photo with?
