### ISSUE TITLE
How to moderate a discussion on a controversional or wide-reaching pull request without everything blowing up

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#335]
Inspired by some recent @cameronmcefee -isms:

* Ground rules up front
* Timeline specified
* Moderator specified
* Decider specified
* Questions or pull requests
  * No place for the peanut gallery
  * If you don't care strongly enough to open a PR and propose an alternative, shouldn't be commenting
  * But see, raises the barrier to entry for non-technical users
* [Give a fuck scale](http://blog.capwatkins.com/the-sliding-scale-of-giving-a-fuck)

**Comment by cameronmcefee** [comment]
Credit goes to @stephbwills for showing me the give-a-fuck scale. I sure do love it though.
