### ISSUE TITLE
404 on article

### ISSUE THREAD

**Issue by gjtorikian** [benbalter/benbalter.github.com#355]
HTML-Proofer has used this link in its tests: http://ben.balter.com/2014/10/08/why-government-contractors-should-%3C3-open-source/

But the URL is now: http://ben.balter.com/2014/10/08/why-government-contractors-should-3-open-source/

Looks like the `<` disappeared.

**Comment by benbalter** [comment]
Via https://github.com/benbalter/benbalter.github.com/commit/eb9b549c50bff3201492a7ed9b99f7068806409d, it now redirects to the new URL. 

Suspect this is a Jekyll 2 -> 3 behavior change.
