### ISSUE TITLE
Mixing of first level heading in posts

### ISSUE THREAD

**Issue by IanLee1521** [benbalter/benbalter.github.com#360]
This is related to my pull, #359.

The blog posts throughout the site use use a mixture of starting with h2 or h3 as the first level of heading in a post. Would there be any desire for a PR (I'd be willing to do it) to re-heading-ize all of the posts to consistently start with either h2 or h3 as the first heading?

In a related thought, would it make sense to change some of the "headings" that you're doing as `**bold markdown**` (example is line 28 of [this post](https://github.com/benbalter/benbalter.github.com/blob/master/_posts/2010-11-15-will-federal-contracting-officers-soon-have-their-heads-in-the-clouds.md#L28)) into the appropriate `<h*>` tag, thus allowing the benefits of deep linking them? Would be easiest to do it at the same time as above, so that's why I bring it up.

**Comment by benbalter** [comment]
> In a related thought, would it make sense to change some of the "headings" that you're doing as **bold markdown** (example is line 28 of this post) into the appropriate <h*> tag, thus allowing the benefits of deep linking them?

Opened https://github.com/wooorm/remark-lint/pull/48 to fix this upstream (I use Remark to lint the Markdown).

**Comment by benbalter** [comment]
Wrote a quick script.... fixed via https://github.com/benbalter/benbalter.github.com/commit/a8ff86d143fee61e589b6466b4a243931e952b1b and https://github.com/benbalter/benbalter.github.com/commit/b2e0cd26a8e958f9cf8425f11302dc578ca1b472. Thanks again @IanLee1521!

**Comment by IanLee1521** [comment]
Great thanks @benbalter! Don't suppose you could share that script? I'd be curious what you did to automate that, maybe just as a gist?  Cheers.

**Comment by benbalter** [comment]
>  Don't suppose you could share that script?

Mostly just `awk` and `sed`, with a little of Atom's global find/replace to clean things up. Wish it was more exciting. :smile: Thanks again!
