### ISSUE TITLE
Design philosophy

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#371]
1. Absorb complexity on behalf of users
2. Optimize for the ideal use case, not the most common
3. Build features 80% of users will use
4. Let the user make the change
5. Always provide an out
6. LIDO
7. Dog food
8. Ship 0.1, not 1.0

**Comment by sroberts** [comment]
Man this is a killer list.

**Comment by benbalter** [comment]
Thanks. Published post: http://ben.balter.com/2016/08/22/ten-ways-to-make-a-product-great/
