### ISSUE TITLE
ruby version

### ISSUE THREAD

**Issue by keegoid** [benbalter/benbalter.github.com#374]
Ben, thanks so much for your model work! Since reading about what you've been doing from @konklone, I've become quite interested in following in your footsteps and writing in public. Living in China the last four years, I can appreciate the value of open source writing and the American freedoms we often take for granted.

*Question*
I noticed your Jekyll site requires ruby version 2.3.0. Is there a reason you don't match the ruby version on GitHub Pages (2.1.7-github)?

I've recently started using rbenv with the [ruby-build-github](https://github.com/parkr/ruby-build-github) project. It's pretty slick.

```bash
git clone git://github.com/parkr/ruby-build-github.git ~/.rbenv/plugins/ruby-build-github

# get the latest ruby version compatible with github pages
ruby_v=$(~/.rbenv/bin/rbenv install --list | grep github$ | tail -1)
```

Kind Regards,
Keegan

**Comment by benbalter** [comment]
Just sanity on my local system. No reason you can't safely delete the file or change to something > 2.
