### ISSUE TITLE
Why is Jekyll appending meta http-equiv attribute?

### ISSUE THREAD

**Issue by MilanAryal** [benbalter/benbalter.github.com#383]
#### Why is Jekyll appending HTML 4.01 `<meta http-equiv="content-type" content="text/html; charset=UTF-8">` in your every page, when you have already included HTML 5 `<meta charset="utf-8">`

![capture1](https://cloud.githubusercontent.com/assets/9361180/15396782/542f1f82-1dfd-11e6-8cf8-17cf7b017726.PNG)

#### ...you do not have any rules in your `default.html` layout to generate meta http-equiv attribute

![capture2](https://cloud.githubusercontent.com/assets/9361180/15397071/79144f56-1dfe-11e6-9014-fde45e221740.PNG)

*This same problem is also creating in my GitHub Pages so I am asking this issue. Thank you!*

**Comment by benbalter** [comment]
I'm at a loss. @parkr any ideas? I checked Kramdown and Jekyll, and other than default templates, I'm not seeing any reference to `http-equiv` to any of the code in the stack.

**Comment by parkr** [comment]
@benbalter Could this be from `html-pipeline`? We shouldn't be modifying the `<head>`, but 💻 .

**Comment by benbalter** [comment]
Oh, I bet it's Nokigiri parsing the doc. @MilanAryal can you create the issue with jekyll-mentions and jemoji disabled?

**Comment by milanaryal** [comment]
@benbalter What I get is `<meta http-equiv="content-type" content="text/html; charset=UTF-8">` is not added in the page, when `jekyll-mentions` and `jemoji` plugins are disabled.

---

#### In my case, `<meta http-equiv="content-type" content="text/html; charset=UTF-8">` is only added in the page where I use jemoji ...and also `<!doctype html>` is replaced with `<!DOCTYPE html>`

![capture-1](https://cloud.githubusercontent.com/assets/9361180/15414429/3955589a-1e5a-11e6-84d9-c38f9e59a2fc.PNG)

#### It's fine, if jemoji is disabled

![capture-2](https://cloud.githubusercontent.com/assets/9361180/15414455/5c3bf2ce-1e5a-11e6-8bb9-411c995841fc.PNG)

**Comment by benbalter** [comment]
@MilanAryal It appears to be an issue with Jemoji. Would you mind opening an issue there?

**Comment by milanaryal** [comment]
@benbalter Done.

**Comment by benbalter** [comment]
Closing in favor of https://github.com/jekyll/jemoji/issues/41.
