### ISSUE TITLE
Everything an open source maintainer needs to know about open source licensing

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#443]
Like https://ben.balter.com/2014/10/08/open-source-licensing-for-government-attorneys/, but less government focused.

* Patents
* GPL
* Copyright versus license
* TOS on GItHub
* CLA
* Distinct Legal entitiy
* Follow the money

**Comment by lee-dohm** [comment]
**Q:** If I fork a project (in the traditional sense as opposed to the GitHub sense), what is the expectation for me to include in the copyright/license/readme/other documentation? Do I add my name to the original copyright line in the license? Do I include some note in the README that the code originated somewhere else? Something else? All of the above?

**Comment by lee-dohm** [comment]
**Q:** Why do end-user applications like [Atom](https://atom.io) have huge license documents that list every component and sub-component and sub-sub-component but other times (most notably when writing a library) only the license for the actual component is included? How do I know when to do which?

**Comment by mlinksva** [comment]
_Needs_ seems too strong. Disproved by existence of successful open source maintainers who know zero or less about most of the topics listed. Maybe _might need_? 😁

**Comment by benbalter** [comment]
WIP over in https://github.com/benbalter/benbalter.github.com/pull/445.

**Comment by benbalter** [comment]
❤️ 
> what is the expectation for me to include in the copyright/license/readme/other documentation? Do I add my name to the original copyright line in the license? Do I include some note in the README that the code originated somewhere else? Something else? All of the above?

Kinda covered that. TL;DR: It depends on the particular licenses requirements. Some e.g., require documenting changes (which I argue a Git history is sufficient to do).

> Why do end-user applications like Atom have huge license documents that list every component and sub-component and sub-sub-component but other times (most notably when writing a library) only the license for the actual component is included? How do I know when to do which?

Again, depends on the license. Some require that all derivative works require a copy of the upstream project's license, others require only copyright, others nothing.

> Needs seems too strong. Disproved by existence of successful open source maintainers who know zero or less about most of the topics listed. Maybe might need? 

👍

**Comment by benbalter** [comment]
https://ben.balter.com/2017/11/28/everything-an-open-source-maintainer-might-need-to-know-about-open-source-licensing/
