### ISSUE TITLE
being ben balter

### ISSUE THREAD

**Issue by doktorbro** [benbalter/benbalter.github.com#493]
the footer of your pages reminds me on _being john malkovich_. i don’t think the repetition was intended.

![being-ben-balter](https://user-images.githubusercontent.com/3617307/95366776-2d3d1980-08d4-11eb-89b5-fe0db61665c9.png)

below the [first post](https://ben.balter.com/2010/09/12/wordpress-resume-plugin/) the ben gallery is broken.

![being-ben-balter-post-first](https://user-images.githubusercontent.com/3617307/95368393-5bbbf400-08d6-11eb-8d92-05af12271c30.png)

**Comment by benbalter** [comment]
Ha! Thanks for opening this. I had no idea. 

Reading through the Disqus docs, I removed the `og:image` property from every page, which should cause Disqus to fallback to a generic, keyword relevant image as soon as their cache refreshes. 🤞🏻

**Comment by doktorbro** [comment]
this is a cautionary tale about embeding external dynamic resources into static websites.
