### ISSUE TITLE
Are we a More Agile Government?

### ISSUE THREAD

**Issue by DaveSkender** [benbalter/benbalter.github.com#513]
I’ve been reading your article [Towards a More Agile Government](https://ben.balter.com/2011/11/29/towards-a-more-agile-government) that you wrote almost 10 years ago.  It’s a nice snapshot in time.  I’m trying to decide how much progress has been made since then.

There has been some efforts in programs like the [DoD Platform One](https://p1.dso.mil) and Navy [Black Pearl](https://blackpearl.us), but I suspect there’s still some nagging impediments across the broader spectrum of government agencies.

### Describe the solution you'd like

A blog post that revisits this topic with observations on progress in government and what you’ve learned since writing it.

### Additional context

I’m a PIF

**Comment by Cyprien-Saito** [comment]
Sir, sorry, but I’m afraid of have to informe you that it is obviously not
of my writing and the vision exposed there is also not of mine.
Kind Regards,
Cyprien Saito


Le sam. 24 juil. 2021 à 14:13, Dave Skender ***@***.***> a
écrit :
