### ISSUE TITLE
Edit links in footer point to the wrong GitHub page

### ISSUE THREAD

**Issue by IanLee1521** [benbalter/benbalter.github.com#528]
### Describe the bug

Edit links at bottom of posts are pointing to the wrong place.

### Steps to reproduce the behavior

1. Go to https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/
2. Scroll down to the footer, and look for the `This page is open source. Please [help improve it](https://github.com/benbalter/benbalter.github.com/edit/main/_posts/2010-09-12-wordpress-resume-plugin.md).` link.
3. Observe that the edit page being linked to is wrong.

### Expected behavior

The "Edit" button should link to: https://github.com/benbalter/benbalter.github.com/edit/main/_posts/2014-11-06-rules-of-communicating-at-github.md

### Screenshots

![image](https://user-images.githubusercontent.com/828452/156261003-f458bc5d-f499-4777-98a8-6cd59f161662.png)

### Additional context

It looks like the page is linking to the "first" blog post.

**Comment by benbalter** [comment]
Good catch! - Thank you for taking the time to open an issue. 

This should be fixed via https://github.com/benbalter/retlab/commit/ace4092a8bf6f14068ff7ba4f5143da3db4ce97c on the next build.

It was an issue with the edit link being cached when the bio include was being cached.

**Comment by IanLee1521** [comment]
Yep! Looks good, thanks!
