### ISSUE TITLE
Syntax code highlighting causes bug with <div> and <pre> tags

### ISSUE THREAD

**Issue by opattison** [benbalter/benbalter.github.com#67]
It only seems to be happening on [one blog post](http://ben.balter.com/2013/06/26/how-to-convert-shapefiles-to-geojson-for-use-on-github/) with console and ruby highlighting, but my guess is that it's the ordered list items that are conflicting with the liquid tags. The list items have paragraph tags within which might also be contributing to the issue. Is that Kramdown causing the problem?

Example: http://ben.balter.com/2013/06/26/how-to-convert-shapefiles-to-geojson-for-use-on-github/

![screen shot 2013-08-08 at 00 29 05 am](https://f.cloud.github.com/assets/885300/929430/3dabe302-ffe3-11e2-9b37-2d37e6c3b307.png)

Great post, by the way.

**Comment by benbalter** [comment]
Fixed in eb0472d5f610e4962bcc0ba4db60dc14128f8ddb. Thanks for the heads up.
