### ISSUE TITLE
Fix use of "comprised of" in 2023-01-10-manage-like-an-engineer.md

### ISSUE THREAD

**Issue by amatlack** [benbalter/benbalter.github.com#728]
I would have fixed directly, but I don't need to fork your repo... just need to remediate the horror that is "[comprised of](https://www.grammarly.com/blog/comprise-vs-compose/)". ;)

https://github.com/benbalter/benbalter.github.com/blob/main/_posts/2023-01-10-manage-like-an-engineer.md

Current:
> Socializes organizational culture and values - An organization's culture and values is **comprised in large part of** 

Proposed: 
> Socializes organizational culture and values - An organization's culture and values is **composed in large part of**

**Comment by benbalter** [comment]
[Fixed](https://github.com/benbalter/benbalter.github.com/commit/01c5f9bb9ff013e0100be9914e8243053118dd58)
