### ISSUE TITLE
Dat design :heart:

### ISSUE THREAD

**Issue by jglovier** [benbalter/benbalter.github.com#96]
In the spirit of open source improvements, I'd love to level up your site design. It would make a fun spare time project for me, and your site is already not to shabby, so with some simple tweaks I think we could take dat game up a notch or two.

Here's some basics I'm thinking about:
- typography and layout
- some stronger images
- other little tweaks tbd

A few things I'll need you to provide are:
- [ ] a larger hero graphic (could be the uncropped, full-resolution original of the existing hero; it's a decent photo)
- [ ] any additional really solid photos you have of yourself "doing yo thang"

I'll fork and futz around. Once I have some things worked up I'll open a PR for discussion and feedback, etc. :zap:

**Comment by benbalter** [comment]
![yessssssss](http://gifs.joelglovier.com/excited/yes-github-yissssss.gif)

> a larger hero graphic (could be the uncropped, full-resolution original of the existing hero; it's a decent photo)

![wp](https://f.cloud.github.com/assets/282759/1926219/3570ddda-7e3e-11e3-950e-14781a8a8d57.jpeg)

> any additional really solid photos you have of yourself "doing yo thang"

On it

//cc Photographer @aaronjorbin

**Comment by benbalter** [comment]
Would have to secure the rights to it, but here's another potential header image:

![20131106_redhat_preview_024](https://f.cloud.github.com/assets/282759/2059058/8efb1a56-8b94-11e3-8349-368cb2073d1e.jpg)

**Comment by jglovier** [comment]
Score! Great photo, if you can get the permission I'd love to use that one. That's a baller shot - your face is in full view, you're addressing an audience, the words "Government Symposium" appear in plain view, and Wordpress is NOT in plain view. Win-win-win-win. :smile: :zap: :thumbsup:

**Comment by benbalter** [comment]
> if you can get the permission I'd love to use that one. 

Per @camilletuutti‎, if we credit via http://ben.balter.com/fine-print/, we're :+1:

**Comment by aaronjorbin** [comment]
@jglovier Why is unhighlighting Ben's involvement and contribution to WordPress a win? 

I worry that the bokeh in this other picture doesn't make it a great header image. It is a great picture of @benbalter, but "Government Symposium" doesn't appear in plain view (it's quite blurred) and all the red hat logos (which are also blurred but can be made out) make it appear that Ben works at or is being sponsored/supported by Red Hat. 

I'm also not a huge fan of the suit.  I think the tie and github hoodie is much more on brand for Ben.

**Comment by jglovier** [comment]
> @jglovier Why is unhighlighting Ben's involvement and contribution to WordPress a win?

Only because it's not something he is actively focused on at GitHub these days.

> I worry that the bokeh in this other picture doesn't make it a great header image. It is a great picture of @benbalter, but "Government Symposium" doesn't appear in plain view (it's quite blurred) and all the red hat logos (which are also blurred but can be made out) make it appear that Ben works at or is being sponsored/supported by Red Hat.
> 
> I'm also not a huge fan of the suit. I think the tie and github hoodie is much more on brand for Ben.

Personally, I didn't notice any of those other things as concerns. I'll defer to @benbalter for whether you want to let those things keep you from using this pic. 

FWIW, I think the suit is appropriate for Ben as it reflects the type of constituents he is frequently working with (the govt crowd) and matches the look he has in his avatar, although I wouldn't be opposed to a more casual one either. 

As for the RedHat background, I think most people would just assume he is speaking at an event sponsored by RedHat. 

Either way, it's a stronger photo on a number of fronts than the current one, but if there's an even better photo available then I'm :thumbsup: for that too.
